### ISSUE TITLE
Livestatus not enabled in Consol-package for Ubuntu 14.04

### ISSUE THREAD

**Issue by aquamoth** [naemon/naemon#44]
After installation, I have this in naemon.cfg:#broker_module=/usr/lib/naemon/naemon-livestatus/livestatus.so /var/cache/naemon/live

This causes Thruk not to find the backend.
Enabling the line and restarting naemon solves the issue. This should be default when installing with Thruk as a default frontend.

**Comment by sni** [comment]
This is the default already. Whenever you install naemon-core or naemon-livestatus, the naemon.cfg is changed in
https://github.com/naemon/naemon/blob/master/debian/naemon-livestatus.postinst
We had to change the spec file, because when install the naemon meta package, sometime the livestatus pkg was installed before the core pkg, even if there are proper dependencies set, and thus
livestatus could not enable itself in the naemon.cfg because at that point it wasn't installed yet.
So in the spec file we do that check in the %post of core and livestatus. On Ubuntu we never had such issues yet and livestatus was always installed after the core. Could you verify that?
