### ISSUE TITLE
Naemon: periodic load spikes

### ISSUE THREAD

**Issue by hkowallik** [naemon/naemon#79]
Environment: RHEL 7, VMware, Naemon 1.0.6, RPM installation

Our naemon servers show massive load spikes - load going up to over 50 on a 4 CPU instance - at more or less periodic intervals.
![naemon_load_spikes](https://user-images.githubusercontent.com/19286113/31598094-09ac80f0-b24c-11e7-881b-dd68412cfa7b.png)
The server is performing 80 checks per second (1000 hosts and 20000 services). Currently active checks only.

There is no correlation to other metrics on the server (cpu usage, number of threads, network IO, disk IO) or performance data on the underlying VMware platform.
It is naemon that causes the load spikes. I shut down all other custom services (lmd, thruk, apache, logstash) running on the server and the load spike were still there.
I also tried the 

The load spikes don't seem to have a negative effect on the operation of naemon but I had to reconfigure sendmail to send mails during high load.

Should I be worried?

**Comment by biscuitNinja** [comment]
We have a similar issue - periodic load average spikes. They are however a fixed 21 minutes apart, on two different nagios servers (different datacentres), on differing hardware.

One server is virtualised, four cores (no HT) with a workload of 93 hosts and 1830 services (~ 31 service checks per second), SAN backed SSD RAID 10 storage.

The other server is physical, 8 cores (+ HT) with a workload of 133 hosts and 2335 services (~38 service checks per second), SSD RAID 1 storage

![image](https://user-images.githubusercontent.com/10847945/36812069-d50879ee-1cc7-11e8-8b99-3c4cb68a8335.png)

Again, there's absolutely no correlation with any other metrics on the server. We get very similar load averages and the exact same periodicity on both servers. The issue is common to both nagios core 3.5.1 and naemon 1.0.6. It persists with perfdata processing disabled.

The Core scheduling graph shows checks to be fairly evenly distributed (more variation under nagios core). Attempts to profile during the high load period shows naemon starting quite a number of fairly short-lived threads. There's no obvious smoking gun in terms of processes hogging CPU cycles etc. and all other metrics show the servers to be under utilised and performing very consistently. Any thoughts/help appreciated.

**Comment by steaksauce-** [comment]
On the first graph, it appears to happen for 40 minutes, and an hour after one occurrence ends.  The second graph appears to happen 10-15 minutes roughly ~21 minutes. You could use dstat and top on a cron schedule to match the times/intervals and check to see what the output is. While it is most likely Naemon or Nagios (as that seems to be what is common between the two reports), it may give you some insight. You can check for other things going on during those times as well... it's a long shot, but given the intervals and lengths are the same across the spikes, maybe you are performing backups at these times?

**Comment by sni** [comment]
Such load spikes are quite common and nothing to worry about. You may also have a look at Thruks core-scheduling plugin (https://thruk.org/documentation/plugins.html#core-scheduling-graph) to get a detailed insight into the scheduling. It also offers commands to balance plugins execution.

**Comment by mintsoft** [comment]
@biscuitNinja what's the average check-interval of nagios checks? Is it 20 minutes?
